server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: accp
    hikari:
      idle-timeout: 6000
      maximum-pool-size: 50
      minimum-idle: 10
  jackson:
    date-format: yyyy-MM-dd
